---
- include: ./receive_key.yml

- name: Download RVM installer
  get_url:
    url: "{{rvm_url}}"
    dest: "{{rvm_temp_installer_path}}"

- name: Set RVM installer to be executable
  file:
    path: "{{rvm_temp_installer_path}}"
    mode: 0755

- name: Install RVM
  command: "{{rvm_temp_installer_path}} --path {{rvm_root}} stable"

- name: Remove RVM installer
  file:
    path: "{{rvm_temp_installer_path}}"
    state: absent

- name: Set RVM autolibs option
  command: "{{rvm_root}}/bin/rvm autolibs {{rvm_autolibs}}"
