---
- include: ./receive_key.yml

- name: downloading RVM installer
  get_url:
    url: "{{rvm_url}}"
    dest: "{{rvm.temp_installer_path}}"

- name: set executable RVM installer
  file:
    path: "{{rvm.temp_installer_path}}"
    mode: 0755

- name: installing RVM
  command: "{{rvm.temp_installer_path}} --path {{rvm_root}} stable"

- name: removing RVM installer
  file:
    path: "{{rvm.temp_installer_path}}"
    state: absent

- name: setting RVM autolibs on
  command: "{{rvm_root}}/bin/rvm autolibs 3"
