---
- include: ./install_packages.yml

- name: checking that RVM is installed
  shell: cat "{{rvm_init_script}}"
  ignore_errors: True
  failed_when: False
  register: rvm_install_result

- include: ./install_rvm.yml
  when: rvm_install_result.rc != 0

- include: ./update_rvm.yml
  when: rvm_auto_update_rvm and rvm_install_result.rc == 0

- include: ./select_ruby.yml

- include: ./install_ruby.yml
  when: rvm_select_ruby_version.rc != 0
