---
- name: Include install type vars
  include_vars: "{{ rvm_install_type }}.yml"

- include_tasks: ./install_packages.yml

- name: Check if RVM installed
  stat:
    path: "{{rvm_init_script}}"
  ignore_errors: True
  failed_when: False
  register: rvm_install_result

- include_tasks: ./install_rvm.yml
  when: rvm_install_result.stat.exists != true

- include_tasks: ./update_rvm.yml
  when: rvm_auto_update_rvm and rvm_install_result.stat.exists == true

- include_tasks: ./select_ruby.yml

- include_tasks: ./install_ruby.yml
  when: rvm_select_ruby_version is defined and rvm_select_ruby_version.rc != 0
