---
- name: setting default Ruby version
  shell: "source {{rvm_init_script}} && rvm use {{rvm_ruby_version}} --default executable=/bin/bash"
  register: rvm_select_ruby_version
  ignore_errors: True
  failed_when: False
  changed_when: False
