---
- name: setting default Ruby version as root
  shell: "source {{rvm.init_script}} && rvm use {{rvm.default_ruby_version}} --default executable=/bin/bash"
  sudo: true
  register: rvm_select_ruby_version_root
  ignore_errors: True
  changed_when: False
  when: rvm.system_install

- name: setting default Ruby version as user
  shell: "source {{rvm.init_script}} && rvm use {{rvm.default_ruby_version}} --default executable=/bin/bash"
  sudo: false
  register: rvm_select_ruby_version_user
  ignore_errors: True
  changed_when: False
  when: not rvm.system_install