---
- name: Check if desired Ruby installed and default
  shell: "source {{rvm_init_script}} && rvm use {{rvm_default_ruby_version}} --default executable=/bin/bash"
  register: rvm_select_ruby_version
  ignore_errors: True
  failed_when: False
  changed_when: False
