---
- include: ./receive_key.yml

- name: updating RVM as root
  shell: "source {{rvm.init_script}} && rvm get stable executable=/bin/bash"
  sudo: true
  when: rvm.system_install

- name: updating RVM as user
  shell: "source {{rvm.init_script}} && rvm get stable executable=/bin/bash"
  sudo: false
  when: not rvm.system_install